### PR TITLE
API stage detail

### PR DESCRIPTION
**Pull request by manhnv-1320**
## Related Tickets
- [ticket redmine](https://edu-redmine.sun-asterisk.vn/issues/71200)

## HOW
- api stage detail using method get in StageDetail class.

## Evidence (Screenshot or Video)
image

### CODE REVIEW

**Comment by manhnv-1320** [comment]
ready

**Comment by huongnt-2545** [comment]
- Check quyền: tất cả member thuộc project đều có thể view detail stage
- Update response: trả về list tasks thuộc stage, list members thuộc stage

**Comment by manhnv-1320** [comment]
image

**Comment by manhnv-1320** [comment]
ready

**Review by quocquann — APPROVED** [review]

**Review by huongnt-2545 — APPROVED** [review]

**Pull request merged**
