### PR TITLE
Add user to project

### PR DESCRIPTION
**Pull request by quocquann**
## Related Tickets
[- ticket redmine](https://edu-redmine.sun-asterisk.vn/issues/70935)

## HOW
Add user by email and send email to user

### CODE REVIEW

**Comment by quocquann** [comment]
ready

**Review by manhnv-1320 — APPROVED** [review]

**Review by huongnt-2545 — APPROVED** [review]
merged

**Comment by huongnt-2545** [comment]
conflicted

**Comment by quocquann** [comment]
ready

**Pull request merged**
