### PR TITLE
API add member to stage

### PR DESCRIPTION
**Pull request by manhnv-1320**
## Related Tickets
- [ticket redmine](https://edu-redmine.sun-asterisk.vn/issues/71186)

## HOW
- add member to stage, body: user_id

## Evidence (Screenshot or Video)
image

### CODE REVIEW

**Comment by manhnv-1320** [comment]
ready

**Comment by manhnv-1320** [comment]
image

**Comment by manhnv-1320** [comment]
ready

**Comment by huongnt-2545** [comment]
conflicted

**Comment by manhnv-1320** [comment]
ready

**Review by huongnt-2545 — APPROVED** [review]

**Pull request merged**
