### PR TITLE
Sign up

### PR DESCRIPTION
**Pull request by manhnv-1320**
## Related Tickets
- [ticket redmine](https://edu-redmine.sun-asterisk.vn/issues/70915)

## WHAT (optional)
- Sign up

## HOW
- sign up with email verification.

### CODE REVIEW

**Comment by manhnv-1320** [comment]
ready

**Comment by huongnt-2545** [comment]
conflicted

**Comment by manhnv-1320** [comment]
ready

**Review by huongnt-2545 — APPROVED** [review]
merged

**Pull request merged**
